-- "DATA".T_BT01_RECEPCION_ORDEN_DETALLE definition

CREATE TABLE "DATA"."T_BT01_RECEPCION_ORDEN_DETALLE" 
   (	"ID" NUMBER(38,0), 
	"IDRECEPCIONORDENCOMPRA" NUMBER(38,0), 
	"ESTADO" VARCHAR2(8), 
	"DESCRIPCION" VARCHAR2(512), 
	"FECHA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_DATA" ;

COMMENT ON TABLE "DATA".T_BT01_RECEPCION_ORDEN_DETALLE IS 'Tabla con el detalle de interaccion de la orden de detalle @author bestech';
COMMENT ON COLUMN "DATA".T_BT01_RECEPCION_ORDEN_DETALLE.ID IS 'Id';
COMMENT ON COLUMN "DATA".T_BT01_RECEPCION_ORDEN_DETALLE.IDRECEPCIONORDENCOMPRA IS 'Id Orden de Compra';
COMMENT ON COLUMN "DATA".T_BT01_RECEPCION_ORDEN_DETALLE.ESTADO IS 'Estado del proceso';
COMMENT ON COLUMN "DATA".T_BT01_RECEPCION_ORDEN_DETALLE.DESCRIPCION IS 'Descripcion del paso';
COMMENT ON COLUMN "DATA".T_BT01_RECEPCION_ORDEN_DETALLE.FECHA IS 'Fecha de ingreso del proceso';