-- "DATA".T_BT01_ARTICULO_DETALLE definition

CREATE TABLE "DATA"."T_BT01_ARTICULO_DETALLE" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"IDARTICULO" NUMBER(38,0) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(8) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(512) NOT NULL ENABLE, 
	"FECHA" TIMESTAMP (6) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_DATA" ;

COMMENT ON TABLE "DATA".T_BT01_ARTICULO_DETALLE IS 'Tabla para el ingreso y actualizacion de datos de articulos y detalle del trabajo';
COMMENT ON COLUMN "DATA".T_BT01_ARTICULO_DETALLE.ID IS 'ID';
COMMENT ON COLUMN "DATA".T_BT01_ARTICULO_DETALLE.IDARTICULO IS 'Id articulo';
COMMENT ON COLUMN "DATA".T_BT01_ARTICULO_DETALLE.ESTADO IS 'Estado del proceso';
COMMENT ON COLUMN "DATA".T_BT01_ARTICULO_DETALLE.DESCRIPCION IS 'Descripcion del paso';
COMMENT ON COLUMN "DATA".T_BT01_ARTICULO_DETALLE.FECHA IS 'Fecha de ingreso del proceso';