
package jp420000.bssv.e1.oracle;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebFault(name = "BusinessServiceException", targetNamespace = "http://oracle.e1.bssv.JP420000/")
public class BusinessServiceException_Exception extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private BusinessServiceException faultInfo;

    /**
     *
     * @param faultInfo
     * @param message
     */
    public BusinessServiceException_Exception(String message, BusinessServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BusinessServiceException_Exception(String message, BusinessServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return
     *     returns fault bean: jp420000.bssv.e1.oracle.BusinessServiceException
     */
    public BusinessServiceException getFaultInfo() {
        return faultInfo;
    }

}
