
package jp420000.bssv.e1.oracle;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "SalesOrderManagerService", targetNamespace = "http://oracle.e1.bssv.JP420000/",
                  wsdlLocation =
                  "https://192.168.5.111:8082/DV900/SalesOrderManager/#%7Bhttp%3A%2F%2Foracle.e1.bssv.JP420000%2F%7DSalesOrderManagerService?wsdl")
public class SalesOrderManagerService extends Service {

    private final static URL SALESORDERMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SALESORDERMANAGERSERVICE_EXCEPTION;
    private final static QName SALESORDERMANAGERSERVICE_QNAME =
        new QName("http://oracle.e1.bssv.JP420000/", "SalesOrderManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://192.168.5.111:8082/DV900/SalesOrderManager/#%7Bhttp%3A%2F%2Foracle.e1.bssv.JP420000%2F%7DSalesOrderManagerService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SALESORDERMANAGERSERVICE_WSDL_LOCATION = url;
        SALESORDERMANAGERSERVICE_EXCEPTION = e;
    }

    public SalesOrderManagerService() {
        super(__getWsdlLocation(), SALESORDERMANAGERSERVICE_QNAME);
    }

    public SalesOrderManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SALESORDERMANAGERSERVICE_QNAME, features);
    }

    public SalesOrderManagerService(URL wsdlLocation) {
        super(wsdlLocation, SALESORDERMANAGERSERVICE_QNAME);
    }

    public SalesOrderManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SALESORDERMANAGERSERVICE_QNAME, features);
    }

    public SalesOrderManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SalesOrderManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SalesOrderManager
     */
    @WebEndpoint(name = "SalesOrderManagerPort")
    public SalesOrderManager getSalesOrderManagerPort() {
        return super.getPort(new QName("http://oracle.e1.bssv.JP420000/", "SalesOrderManagerPort"),
                             SalesOrderManager.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SalesOrderManager
     */
    @WebEndpoint(name = "SalesOrderManagerPort")
    public SalesOrderManager getSalesOrderManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://oracle.e1.bssv.JP420000/", "SalesOrderManagerPort"),
                             SalesOrderManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SALESORDERMANAGERSERVICE_EXCEPTION != null) {
            throw SALESORDERMANAGERSERVICE_EXCEPTION;
        }
        return SALESORDERMANAGERSERVICE_WSDL_LOCATION;
    }

}
