
package jp594205.bssv.e1.oracle;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "ShippingConfirmation", targetNamespace = "http://oracle.e1.bssv.JP594205/")
@XmlSeeAlso({ ObjectFactory.class })
public interface ShippingConfirmation {


    /**
     *
     * @param dataItem
     * @param ediDocumentType
     * @param ediDocumentNumber
     * @param jdEnterpriseOneEventPoint01
     * @param version
     * @param companyKeyEDIDocumentKeyCo
     * @throws BusinessServiceException_Exception
     */
    @WebMethod(operationName = "SalesShippingConfirmation")
    @RequestWrapper(localName = "SalesShippingConfirmation", targetNamespace = "http://oracle.e1.bssv.JP594205/",
                    className = "jp594205.bssv.e1.oracle.VoD554205A1INPUT")
    @ResponseWrapper(localName = "SalesShippingConfirmationResponse",
                     targetNamespace = "http://oracle.e1.bssv.JP594205/",
                     className = "jp594205.bssv.e1.oracle.VoD554205A1OUTPUT")
    public void salesShippingConfirmation(@WebParam(name = "companyKeyEDIDocumentKeyCo", targetNamespace = "")
                                          String companyKeyEDIDocumentKeyCo,
                                          @WebParam(name = "EDIDocumentNumber", targetNamespace = "")
                                          Integer ediDocumentNumber,
                                          @WebParam(name = "EDIDocumentType", targetNamespace = "")
                                          String ediDocumentType,
                                          @WebParam(name = "version", targetNamespace = "") String version,
                                          @WebParam(name = "dataItem", targetNamespace = "", mode = WebParam.Mode.OUT)
                                          Holder<String> dataItem,
                                          @WebParam(name = "JDEnterpriseOneEventPoint01", targetNamespace = "",
                                                    mode = WebParam.Mode.OUT)
                                          Holder<String> jdEnterpriseOneEventPoint01) throws BusinessServiceException_Exception;

}
