<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns:wssutil="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://oracle.e1.bssv.JP594205/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://oracle.e1.bssv.JP594205/" name="ShippingConfirmationService">
  <wsp:UsingPolicy wssutil:Required="true"/>
  <wsp:Policy wssutil:Id="bssvpolicy">
    <ns1:TransportBinding xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
      <wsp:Policy>
        <ns1:TransportToken>
          <wsp:Policy>
            <ns1:HttpsToken/>
          </wsp:Policy>
        </ns1:TransportToken>
        <ns1:AlgorithmSuite>
          <wsp:Policy>
            <ns1:Basic256/>
          </wsp:Policy>
        </ns1:AlgorithmSuite>
        <ns1:Layout>
          <wsp:Policy>
            <ns1:Lax/>
          </wsp:Policy>
        </ns1:Layout>
      </wsp:Policy>
    </ns1:TransportBinding>
    <ns2:SupportingTokens xmlns:ns2="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
      <wsp:Policy>
        <ns2:UsernameToken ns2:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
          <wsp:Policy>
            <ns2:WssUsernameToken10/>
          </wsp:Policy>
        </ns2:UsernameToken>
      </wsp:Policy>
    </ns2:SupportingTokens>
  </wsp:Policy>
  <types>
    <xsd:schema>
      <xsd:import namespace="http://oracle.e1.bssv.JP594205/" schemaLocation="ShippingConfirmation1.xsd"/>
    </xsd:schema>
  </types>
  <message name="SalesShippingConfirmation">
    <part name="SalesShippingConfirmation" element="tns:SalesShippingConfirmation"/>
  </message>
  <message name="SalesShippingConfirmationResponse">
    <part name="SalesShippingConfirmationResponse" element="tns:SalesShippingConfirmationResponse"/>
  </message>
  <message name="BusinessServiceException">
    <part name="fault" element="tns:BusinessServiceException"/>
  </message>
  <portType name="ShippingConfirmation">
    <operation name="SalesShippingConfirmation">
      <input message="tns:SalesShippingConfirmation"/>
      <output message="tns:SalesShippingConfirmationResponse"/>
      <fault message="tns:BusinessServiceException" name="BusinessServiceException"/>
    </operation>
  </portType>
  <binding name="ShippingConfirmationPortBinding" type="tns:ShippingConfirmation">
    <wsp:PolicyReference URI="#bssvpolicy"/>
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="SalesShippingConfirmation">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="BusinessServiceException">
        <soap:fault name="BusinessServiceException" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="ShippingConfirmationService">
    <port name="ShippingConfirmationPort" binding="tns:ShippingConfirmationPortBinding">
      <soap:address location="https://192.168.5.111:8082/DV900/ShippingConfirmation"/>
    </port>
  </service>
</definitions>